export const DETECT_NAVBAR = 'DETECT_NAVBAR';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const TOGGLE_CART_ITEM_AMOUNT = 'TOGGLE_CART_ITEM_AMOUNT';
export const COUNT_CART_TOTALS = 'COUNT_CART_TOTALS';
export const UPDATE_CART = 'UPDATE_CART';

// User
export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';

// Shipping Details
export const CHANGE_SHPPING_DETAIL = 'CHANGE_SHPPING_DETAIL';
export const CLEAR_SHPPING_DETAIL = 'CLEAR_SHPPING_DETAIL';
export const HANDLE_CHANGE_SHIPPING = 'HANDLE_CHANGE_SHIPPING';

// Filters
export const SHOW_LOADING_FILTER = 'SHOW_LOADING_FILTER';
export const GET_FILTERED_ERROR = 'GET_FILTERED_ERROR';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const HANDLE_CHANGE_FILTER = 'HANDLE_CHANGE_FILTER';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const DETECT_FILTER = 'DETECT_FILTER';
